apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql123
  namespace: expense
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql123
        image: manjudbadevops/mysqltest:1.0.0
         configMap:
          name: mysql-config

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-nlb
  namespace: expense
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # For AWS
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # For internal NLB
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
    

----

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: expense
data:
  my.cnf: |
    [mysqld]
    local_infile    = 1

