apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql123
  namespace: expense
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql123
        image: manjudbadevops/mysqltest:1.0.0

---

apiVersion: v1
kind: Service
metadata:
  name: mysql123
  namespace: expense
spec: 
  type: LoadBalancer
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

